### ISSUE TITLE
Crashes on Start

### ISSUE THREAD

**Issue by wikflip** [Mark-Prime/Melies#1] opened 2024-09-29 21:23 UTC
Can't give much more info, as soon as I open it, it closes itself/crashes (can't tell.) Am I doing something wrong?

**Comment by Mark-Prime** [comment] 2024-10-01 21:07
There are a few possible things that could cause it. 

A good first step would be to find your settings.json file in C:\Users\USERNAME\Documents\Melies (MAKE SURE THIS ISNT ONE DRIVE) and deleting/renaming it. It'll remake the settings with default stuff and then load normally as if it was the first time. If that doesn't work I have some questions just to clarify the basics...

Is it opening and then closing immediately or is it not opening at all?

Have you at any point used a tool to try and uninstall Microsoft Edge for any reason?

If you want faster help than I can offer here (this is the first issue on the github so I'd never bothered to check here much before) I recommend going into the discord and messaging me/the support channel. I'm much faster at replying there: https://discord.gg/dxbWgTu

**Comment by Mark-Prime** [comment] 2024-10-02 21:01
We talked in discord and got the issue resolved.

This was caused by a corrupted demo being scanned by the demo manager. The next release will have a check in place to protect against similar crashes and it also now prevents the demo sections from scanning as soon as the program launches. This should make future issues easier to resolve and also improve load times.

**Closed as completed by Mark-Prime** 2024-10-02 21:01 UTC
Labels: bug
